export const ASSEMBLY_CONSTITUENCIES_BY_DISTRICT: Record<string, string[]> = {
  'Ariyalur': ['Ariyalur', 'Jayankondam', 'Sendurai'],
  'Chengalpattu': ['Sholinganallur', 'Pallavaram', 'Tambaram', 'Alandur', 'Chengalpattu', 'Thiruporur', 'Cheyyur', 'Madurantakam'],
  'Chennai': ['Dr. Radhakrishnan Nagar', 'Perambur', 'Kolathur', 'Villivakkam', 'Thiru-Vi-Ka-Nagar', 'Egmore', 'Royapuram', 'Harbour', 'Chepauk-Thiruvallikeni', 'Thousand Lights', 'Anna Nagar', 'Virugambakkam', 'Saidapet', 'T. Nagar', 'Mylapore', 'Velachery'],
  'Coimbatore': ['Mettupalayam', 'Sulur', 'Kavundampalayam', 'Coimbatore North', 'Thondamuthur', 'Coimbatore South', 'Singanallur', 'Kinathukadavu', 'Pollachi', 'Valparai'],
  'Cuddalore': ['Vriddhachalam', 'Neyveli', 'Panruti', 'Cuddalore', 'Kurinjipadi', 'Bhuvanagiri', 'Chidambaram', 'Kattumannarkoil'],
  'Dharmapuri': ['Palacode', 'Pennagaram', 'Dharmapuri', 'Pappireddippatti', 'Harur'],
  'Dindigul': ['Palani', 'Oddanchatram', 'Athoor', 'Nilakkottai', 'Natham', 'Dindigul', 'Vedasandur'],
  'Erode': ['Erode East', 'Erode West', 'Modakkurichi', 'Perundurai', 'Bhavani', 'Anthiyur', 'Gobichettipalayam', 'Bhavanisagar'],
  'Kallakurichi': ['Tirukkoyilur', 'Ulundurpettai', 'Sankarapuram', 'Kallakurichi'],
  'Kancheepuram': ['Sriperumbudur', 'Uthiramerur', 'Kancheepuram'],
  'Kanniyakumari': ['Kanniyakumari', 'Nagercoil', 'Colachel', 'Padmanabhapuram', 'Vilavancode', 'Killiyoor', 'Thiruvattar'],
  'Karur': ['Aravakurichi', 'Karur', 'Krishnarayapuram', 'Kulithalai'],
  'Krishnagiri': ['Uthangarai', 'Bargur', 'Krishnagiri', 'Veppanahalli', 'Hosur', 'Thalli'],
  'Madurai': ['Melur', 'Madurai East', 'Sholavandan', 'Madurai North', 'Madurai South', 'Madurai Central', 'Madurai West', 'Thiruparankundram', 'Thirumangalam', 'Usilampatti'],
  'Mayiladuthurai': ['Sirkazhi', 'Mayiladuthurai', 'Poompuhar'],
  'Nagapattinam': ['Nagapattinam', 'Kilvelur', 'Vedaranyam'],
  'Namakkal': ['Rasipuram', 'Senthamangalam', 'Namakkal', 'Paramathi-Velur', 'Tiruchengode', 'Kumarapalayam'],
  'Nilgiris': ['Udhagamandalam', 'Gudalur', 'Coonoor'],
  'Perambalur': ['Perambalur', 'Kunnam'],
  'Pudukkottai': ['Gandharvakottai', 'Viralimalai', 'Pudukkottai', 'Thirumayam', 'Alangudi', 'Aranthangi'],
  'Ramanathapuram': ['Paramakudi', 'Tiruvadanai', 'Ramanathapuram', 'Mudhukulathur'],
  'Ranipet': ['Arakkonam', 'Sholingur', 'Ranipet', 'Arcot', 'Kaveripakkam'],
  'Salem': ['Gangavalli', 'Attur', 'Yercaud', 'Omalur', 'Mettur', 'Edappadi', 'Sankari', 'Salem West', 'Salem North', 'Salem South', 'Veerapandi'],
  'Sivagangai': ['Karaikudi', 'Tiruppattur', 'Sivaganga', 'Manamadurai'],
  'Tenkasi': ['Sankarankovil', 'Vasudevanallur', 'Kadayanallur', 'Tenkasi', 'Alangulam'],
  'Thanjavur': ['Thiruvidaimarudur', 'Kumbakonam', 'Papanasam', 'Thiruvaiyaru', 'Thanjavur', 'Orathanadu', 'Pattukkottai', 'Peravurani'],
  'Theni': ['Andipatti', 'Periyakulam', 'Bodinayakanur', 'Cumbum'],
  'Thoothukudi': ['Vilathikulam', 'Thoothukudi', 'Tiruchendur', 'Srivaikuntam', 'Ottapidaram', 'Kovilpatti'],
  'Tiruchirappalli': ['Manapparai', 'Srirangam', 'Tiruchirappalli West', 'Tiruchirappalli East', 'Thiruverumbur', 'Lalgudi', 'Manachanallur', 'Musiri', 'Thuraiyur'],
  'Tirunelveli': ['Tirunelveli', 'Ambasamudram', 'Palayamkottai', 'Nanguneri', 'Radhapuram'],
  'Tirupathur': ['Vaniyambadi', 'Ambur', 'Jolarpet', 'Tirupattur'],
  'Tiruppur': ['Dharapuram', 'Kangeyam', 'Tiruppur North', 'Tiruppur South', 'Palladam', 'Udumalpet', 'Madathukulam'],
  'Thiruvallur': ['Tiruvottiyur', 'Gummidipoondi', 'Ponneri', 'Tiruvallur', 'Poonamallee', 'Avadi', 'Madhavaram', 'Ambattur', 'Maduravoyal'],
  'Tiruvannamalai': ['Chengam', 'Tiruvannamalai', 'Kilpennathur', 'Kalasapakkam', 'Polur', 'Arani', 'Cheyyar', 'Vandavasi'],
  'Tiruvarur': ['Thiruthuraipoondi', 'Mannargudi', 'Tiruvarur', 'Nannilam'],
  'Vellore': ['Katpadi', 'Vellore', 'Anaikattu', 'K.V.Kuppam', 'Gudiyattam'],
  'Viluppuram': ['Gingee', 'Mailam', 'Tindivanam', 'Vanur', 'Villupuram', 'Vikravandi', 'Rishivandiyam'],
  'Virudhunagar': ['Rajapalayam', 'Srivilliputhur', 'Sattur', 'Sivakasi', 'Virudhunagar', 'Aruppukkottai', 'Tiruchuli'],
};